import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'

const Home: NextPage = (props: any) => {
//   console.log("assets", assets);
console.log("props", props);
  const { scripts, styles } = props.manifest.entrypoints.reduce((prev: any, current: string) => {
      if (current.indexOf(".css") > -1) {
          return {
              ...prev,
              styles: [...prev.styles, `/_next/static/client/${current}`]
          }
      }
      if (current.indexOf(".js") > -1) {
        return {
            ...prev,
            scripts: [...prev.scripts, `/_next/static/client/${current}`]
        }
    }
      return prev;

  }, { scripts: [], styles: [] })
  return (
    <div>
      <Head>
        <title>Create React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {styles.map((item: string, key: number) => <link key={`cra-style-key-${key}`} rel="stylesheet" href={item} />)}
      </Head>
      {scripts.map((item: string, key: number) => <Script key={`cra-script-key-${key}`} src={item} />)}
      <div id="root" />
    </div>
  );
}

export async function getServerSideProps({ preview = false }) {
    // const allPosts = await getAllPostsForHome(preview)
    const data = await fetch('http://localhost:3000/_next/static/client/asset-manifest.json');
    const manifest = await data.json();
    return {
      props: { preview, manifest },
    }
  }

export default Home
