import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import assets from "../../../client/build/asset-manifest.json";
const Home: NextPage = () => {
  console.log("assets", assets);
  console.log("Index app")
  return (
    <div className={styles.container}>
      <Head>
        <title>Create React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Hello</p>
      </main>
    </div>
  );
}

export default Home
